Feature/issue 829 parallelization error
TNG/JGiven pull request #835
Opened 2022-02-15 06:06 UTC by l-1squared

2022-02-15 08:26 UTC, fudler requested changes

2022-02-15 08:26 UTC, fudler commented on jgiven-core/src/main/java/com/tngtech/jgiven/report/model/ReportModel.java
>              return "";
While refactoring a bit one could maybe use StringUtils here? :)

2022-02-15 08:26 UTC, fudler commented on jgiven-junit5/src/test/java/com/tngtech/jgiven/junit5/test/concurrency/JUnit5InheritedParallelizationTest.java
> +        when().the_state_on_this_thread_is_set_to("I am the greatest" + i);
For convenience, probably there should be some additional space after greatest. The missing space somehow nudges me :D

2022-02-15 08:26 UTC, fudler commented on jgiven-testng/src/test/java/com/tngtech/jgiven/testng/concurrency/TestNgInheritedParallelizationTest.java
> +    public void fistTest() {
Typo

2022-02-23 06:25 UTC, l-1squared commented
Closing because this PR it was supposed to be #842.
The mergeable JUnit5 changes are included there.

2022-02-23 06:25 UTC, closed without merging